# Generated by Django 4.1 on 2022-09-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally2app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='types',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
